import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { NextResponse } from "next/server";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";

export const runtime = "nodejs";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#0f172a",
  },
  header: {
    borderBottom: "2px solid #2563eb",
    paddingBottom: 16,
    marginBottom: 24,
  },
  brand: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#1d4ed8",
  },
  title: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: "bold",
  },
  muted: {
    color: "#64748b",
    marginTop: 4,
  },
  scoreBox: {
    backgroundColor: "#eff6ff",
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
  },
  score: {
    fontSize: 42,
    fontWeight: "bold",
    color: "#1d4ed8",
  },
  section: {
    marginTop: 18,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "bold",
    marginBottom: 8,
  },
  card: {
    border: "1px solid #e2e8f0",
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  footer: {
    marginTop: 30,
    paddingTop: 12,
    borderTop: "1px solid #e2e8f0",
    color: "#64748b",
    fontSize: 9,
  },
});

function getScoreLabel(score: number) {
  if (score >= 90) return "Excellent";
  if (score >= 75) return "Strong";
  if (score >= 60) return "Needs Attention";
  return "Patient Opportunity Risk";
}

function ReportPdf({
  websiteUrl,
  score,
  reportType,
  generatedAt,
}: {
  websiteUrl: string;
  score: number;
  reportType: string;
  generatedAt: string;
}) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>AuditFix Dental</Text>
          <Text style={styles.title}>{reportType}</Text>
          <Text style={styles.muted}>Website analyzed: {websiteUrl}</Text>
          <Text style={styles.muted}>Generated: {generatedAt}</Text>
        </View>

        <View style={styles.scoreBox}>
          <Text>Patient Growth Score</Text>
          <Text style={styles.score}>{score}/100</Text>
          <Text>{getScoreLabel(score)}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>What This Means</Text>
          <Text>
            This report identifies website signals that may affect patient
            trust, local visibility, appointment requests, and mobile
            experience.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Industry Benchmark</Text>

          <View style={styles.card}>
            <Text>Your Practice: {score}</Text>
            <Text>Industry Average: 59</Text>
            <Text>Top Dental Websites: 86</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            Estimated Patient Growth Opportunity
          </Text>

          <View style={styles.card}>
            <Text>Potential impact: 1–5 more inquiries/month</Text>
            <Text>
              This is a directional estimate based on common dental website
              improvement opportunities.
            </Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Recommended Focus Areas</Text>

          <View style={styles.card}>
            <Text>✓ Improve appointment conversion</Text>
            <Text>✓ Strengthen local visibility</Text>
            <Text>✓ Build patient trust</Text>
            <Text>✓ Improve mobile experience</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by AuditFix Dental. This report is for informational and
          planning purposes and does not guarantee specific business results.
        </Text>
      </Page>
    </Document>
  );
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const auditId = body.auditId;
    const reportType = body.reportType || "AuditFix Patient Growth Report";

    if (!auditId || typeof auditId !== "string") {
      return NextResponse.json(
        { error: "Audit ID is required." },
        { status: 400 },
      );
    }

    const { data: audit, error } = await supabaseAdmin
      .from("audits")
      .select("*")
      .eq("id", auditId)
      .single();

    if (error || !audit) {
      return NextResponse.json(
        { error: "Audit report not found." },
        { status: 404 },
      );
    }

    const score =
      audit.deep_scores?.mobilePerformance !== undefined &&
      audit.deep_scores !== null
        ? Math.round(
            (audit.deep_scores.mobilePerformance ?? 0) * 0.4 +
              (audit.deep_scores.seo ?? 0) * 0.25 +
              (audit.deep_scores.accessibility ?? 0) * 0.2 +
              (audit.deep_scores.bestPractices ?? 0) * 0.15,
          )
        : audit.quick_score;

    const pdfBuffer = await renderToBuffer(
      <ReportPdf
        websiteUrl={audit.website_url}
        score={score}
        reportType={reportType}
        generatedAt={new Date().toLocaleDateString()}
      />,
    );

return new Response(
  pdfBuffer.buffer.slice(
    pdfBuffer.byteOffset,
    pdfBuffer.byteOffset + pdfBuffer.byteLength,
  ),
  {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="auditfix-report-${auditId}.pdf"`,
    },
  },
);
  } catch (error) {
    console.error("PDF Report Error:", error);

    return NextResponse.json(
      { error: "Could not generate PDF report." },
      { status: 500 },
    );
  }
}
