import { resend } from "@/lib/resend";
import { NextResponse } from "next/server";

function isValidEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

export async function POST(request: Request) {
  try {
    const body = await request.json();

    const email = body.email;
    const reportUrl = body.reportUrl;
    const websiteUrl = body.websiteUrl;
    const reportTitle = body.reportTitle;

    if (!email || typeof email !== "string" || !isValidEmail(email)) {
      return NextResponse.json(
        { error: "Please enter a valid email address." },
        { status: 400 },
      );
    }

    if (!reportUrl || typeof reportUrl !== "string") {
      return NextResponse.json(
        { error: "Report URL is required." },
        { status: 400 },
      );
    }

    const fromEmail =
      process.env.AUDITFIX_FROM_EMAIL ||
      "AuditFix <onboarding@resend.dev>";

    const normalizedEmail = email.toLowerCase().trim();

    const result = await resend.emails.send({
      from: fromEmail,
      to: normalizedEmail,
      subject: reportTitle || "Your AuditFix report",
      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #0f172a;">
          <h1>Your AuditFix Report</h1>

          <p>Your report for <strong>${websiteUrl || "your website"}</strong> is ready.</p>

          <p>
            <a href="${reportUrl}" style="display: inline-block; background: #1d4ed8; color: white; padding: 12px 18px; border-radius: 10px; text-decoration: none; font-weight: bold;">
              View My Report
            </a>
          </p>

          <p>This report highlights opportunities related to patient trust, local visibility, appointment requests, and mobile experience.</p>

          <p style="color: #64748b; font-size: 13px;">
            Generated by AuditFix Dental.
          </p>
        </div>
      `,
    });

    if (result.error) {
      console.error("Email Report Error:", result.error);

      return NextResponse.json(
        { error: "We could not send the report email. Please try again." },
        { status: 500 },
      );
    }

    return NextResponse.json({
      success: true,
      message: "Report emailed successfully.",
    });
  } catch (error) {
    console.error("Email Report API Error:", error);

    return NextResponse.json(
      { error: "Something went wrong while emailing the report." },
      { status: 500 },
    );
  }
}
