"use client";

import Link from "next/link";
import { useState } from "react";

type ReportActionsProps = {
  reportTitle: string;
  websiteUrl: string;
};

export default function ReportActions({
  reportTitle,
  websiteUrl,
}: ReportActionsProps) {
  const [copied, setCopied] = useState(false);

  function downloadReport() {
    window.print();
  }

  async function copyLink() {
    await navigator.clipboard.writeText(window.location.href);
    setCopied(true);

    window.setTimeout(() => {
      setCopied(false);
    }, 2000);
  }

  const emailSubject = encodeURIComponent(reportTitle);

  const emailBody = encodeURIComponent(
    `I generated an AuditFix report for ${websiteUrl}.

View the report here:
${typeof window !== "undefined" ? window.location.href : ""}

Generated by AuditFix
https://dentist.auditfix.ai`,
  );

  return (
    <section id="fix-plan" className="mt-8 rounded-3xl border border-slate-200 bg-white p-8 shadow-sm print:hidden">
      <div className="flex flex-col gap-8">
        <div>
          <h2 className="text-3xl font-bold text-slate-950">
            What would you like to do next?
          </h2>

          <p className="mt-3 max-w-3xl text-slate-600">
            Save this report, share it with your team, or continue improving
            your patient experience and online visibility.
          </p>
        </div>

        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
          <button
            type="button"
            onClick={downloadReport}
            className="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-left transition hover:bg-blue-100"
          >
            <div className="text-2xl">📥</div>

            <h3 className="mt-3 font-semibold text-slate-950">
              Download / Print Report
            </h3>

            <p className="mt-2 text-sm text-slate-600">
              Save a printable copy of your Patient Growth Report.
            </p>
          </button>

          <a
            href={`mailto:?subject=${emailSubject}&body=${emailBody}`}
            className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:bg-slate-50"
          >
            <div className="text-2xl">📧</div>

            <h3 className="mt-3 font-semibold text-slate-950">
              Email Me This Report
            </h3>

            <p className="mt-2 text-sm text-slate-600">
              Send this report to yourself or your team.
            </p>
          </a>

          <button
            type="button"
            onClick={copyLink}
            className="rounded-2xl border border-slate-200 bg-white p-5 text-left transition hover:bg-slate-50"
          >
            <div className="text-2xl">🔗</div>

            <h3 className="mt-3 font-semibold text-slate-950">
              {copied ? "Link Copied" : "Copy Share Link"}
            </h3>

            <p className="mt-2 text-sm text-slate-600">
              Share this report with colleagues or stakeholders.
            </p>
          </button>

          <Link
            href="/"
            className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:bg-slate-50"
          >
            <div className="text-2xl">🔄</div>

            <h3 className="mt-3 font-semibold text-slate-950">
              Run Another Scan
            </h3>

            <p className="mt-2 text-sm text-slate-600">
              Analyze another practice website.
            </p>
          </Link>

          <a
            href="#fix-plan"
            className="rounded-2xl border border-green-200 bg-green-50 p-5 transition hover:bg-green-100"
          >
            <div className="text-2xl">🛠</div>

            <h3 className="mt-3 font-semibold text-slate-950">
              Get My Custom Fix Plan
            </h3>

            <p className="mt-2 text-sm text-slate-600">
              Receive personalized recommendations for your website.
            </p>
          </a>
        </div>

        <div className="rounded-3xl bg-slate-50 p-8">
          <h3 className="text-2xl font-bold text-slate-950">
            Questions About Your Score?
          </h3>

          <p className="mt-4 max-w-3xl text-slate-600">
            Receive a personalized action plan focused on helping more patients
            find, trust, and contact your practice.
          </p>

          <div className="mt-6 grid gap-3 md:grid-cols-2">
            <div className="rounded-xl bg-white p-4">
              ✓ More appointment requests
            </div>

            <div className="rounded-xl bg-white p-4">
              ✓ Better local visibility
            </div>

            <div className="rounded-xl bg-white p-4">
              ✓ Improved patient trust
            </div>

            <div className="rounded-xl bg-white p-4">
              ✓ Faster mobile experience
            </div>
          </div>

          <div className="mt-8">
            <a
              href="#fix-plan"
              className="inline-flex rounded-xl bg-blue-700 px-6 py-3 font-semibold text-white transition hover:bg-blue-800"
            >
              Get My Custom Fix Plan
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}
